services:
  recommender_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  recommender_app:
    image: recommender_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - recommender_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@recommender_database:5432/app_db

volumes:
  pgdata: